listaErros = {
    0: "identificador mal formado",
    1: "inteiro mal formado",
    2: "inteiro mal formado",
    3: "inteiro mal formado",
    4: "float mal formado",
    5: "float mal formado",
    6: "float mal formado",
    7: "float mal formado",
    8: "float mal formado",
    9: "inteiro mal formado",
    10: "inteiro mal formado",
    11: "float formado",
    12: "data mal formada",
    14: "endereço mal formado",
    15: "data mal formada",
    16: "data mal formada",
    17: "data mal formada",
    18: "data mal formada",
    19: "data mal formada",
    20: "data mal formada",
    21: "data mal formada",
    23: "data mal formada",
    24: "data mal formada",
    25: "data mal formada",
    26: "data mal formada",
    27: "data mal formada",
    28: "data mal formada",
    29: "data mal formada",
    31: "endereço mal formado",
    32: "endereço mal formado",
    34: "cadeia não fechada",
    35: "cadeia não fechada",
    36: "cadeia não fechada",
    37: "identificador mal formado",
    38: "identificador mal formado",
    39: "identificador mal formado",
    40: "identificador mal formado",
    48: "comentário de bloco não fechado",
    49: "comentário de bloco não fechado",
    50: "comentário de bloco não fechado",
    52: "comentário de bloco não fechado",
    51: "comentário de bloco não fechado",
    54: "palavra reservada não encontrada",
    55: "palavra reservada não encontrada",
    56: "operador não encontrado",
    57: "operador não encontrado",
    58: "operador não encontrado",
    59: "operador não encontrado",
    60: "operador não encontrado",
    61: "operador não encontrado",
    62: "operador não encontrado",
    63: "operador não encontrado",
    64: "operador não encontrado",
    65: "operador não encontrado",
    66: "operador não encontrado",
    68: "operador não encontrado",
    70: "operador não encontrado",
    71: "operador não encontrado",
    72: "operador não encontrado",
    74: "operador não encontrado",
    79: "comentário de linha mal formatado",
    81: "comentário de linha mal formatado",
    84: "delimitador não encontrado",
    86: "delimitador não encontrado",
    88: "delimitador não encontrado",
}